Adds workflow to run tests
zkan/testroad pull request #7
Opened 2020-10-08 11:24 UTC by selamanse

Closes #6 

I added a separate workflow to run the tests on PRs and pushes to master.
Looking at the circleci configuration I understood that you were using poetry with python 3.7 to manage the project, so I adopted this to the workflow and all seems to run nicely.

Please have a look and also make suggestions if you need anything else.

2020-10-08 15:01 UTC, zkan requested changes
@selamanse Thanks! I'd request some changes, so that the text style looks consistent.

2020-10-08 15:01 UTC, zkan commented on .github/workflows/run-tests.yml
> +    - name: Style Guide Enforcement
```suggestion
    - name: Style guide enforcement
```

2020-10-08 15:01 UTC, zkan commented on .github/workflows/run-tests.yml
> +    - name: Run Tests
```suggestion
    - name: Run tests
```

2020-10-08 15:05 UTC, selamanse reviewed
👍

2020-10-08 21:21 UTC, selamanse commented
@zkan I cleaned up a little by adding defaults (reducing the duplicate declaration of workspace) and removing comments from the template I used.

2020-10-09 02:13 UTC, zkan approved these changes
Looks great! Thanks. :)

2020-10-09 02:13 UTC, merged